### ISSUE TITLE
WebCrawler data source cannot be created

### ISSUE THREAD

**Issue by mptak-tbscg** [aws-cloudformation/aws-cloudformation-resource-provider-qbusiness#54]
Hello, I encountered an issue while trying to deploy a new data source to my QBusiness application. Due to the lack of complete documentation, I created a resource via the console and retrieved all details about it using the following command:

`aws qbusiness get-data-source --application-id <app-id> --index-id <index-id> --data-source-id <data-source-id>`

here is the output of the command:
 
``` 
applicationId: <app-id>
configuration:
  additionalProperties:
    crawlAllDomain: false
    crawlAttachments: false
    crawlDepth: '2'
    crawlDomainsOnly: false
    crawlSubDomain: true
    exclusionFileIndexPatterns: []
    exclusionURLCrawlPatterns: []
    exclusionURLIndexPatterns: []
    honorRobots: true
    includeSupportedFileType: false
    inclusionFileIndexPatterns: []
    inclusionURLCrawlPatterns: []
    inclusionURLIndexPatterns: []
    maxFileSize: '50'
    maxLinksPerUrl: '100'
    proxy: {}
    rateLimit: '300'
  connectionConfiguration:
    repositoryEndpointMetadata:
      authentication: NoAuthentication
      seedUrlConnections:
      - seedUrl: <seed-url>
  enableIdentityCrawler: false
  repositoryConfigurations:
    attachment:
      fieldMappings:
      - dataSourceFieldName: category
        indexFieldName: _category
        indexFieldType: STRING
      - dataSourceFieldName: sourceUrl
        indexFieldName: _source_uri
        indexFieldType: STRING
    webPage:
      fieldMappings:
      - dataSourceFieldName: category
        indexFieldName: _category
        indexFieldType: STRING
      - dataSourceFieldName: sourceUrl
        indexFieldName: _source_uri
        indexFieldType: STRING
  syncMode: FORCED_FULL_CRAWL
  type: WEBCRAWLER
  version: 1.0.0
createdAt: '2024-06-10T12:34:48.898000+02:00'
dataSourceArn: <arn>
dataSourceId: <id>
description: ''
displayName: test
error: {}
indexId: <index-id>
roleArn: <role-arn>
status: ACTIVE
syncSchedule: ''
type: WEBCRAWLER
updatedAt: '2024-06-10T12:34:48.898000+02:00'
```

I tried to use the output to create a YAML template, so I copied the configuration section and created something like this:

```
QChatWebDataSource:
    Type: AWS::QBusiness::DataSource
    Properties:
      ApplicationId: !Ref QChatBusinessApp
      Configuration:
        additionalProperties:
          crawlDepth: 2
          maxFileSize: 50
          maxLinksPerUrl: 100
          rateLimit: 300
          proxy: {}
          exclusionURLCrawlPatterns: []
          exclusionURLIndexPatterns: []
          exclusionFileIndexPatterns: []
          inclusionURLCrawlPatterns: []
          inclusionURLIndexPatterns: []
          inclusionFileIndexPatterns: []
          includeSupportedFileType: false
          crawlSubDomain: true
          crawlAllDomain: false
          honorRobots: true
        connectionConfiguration:
          repositoryEndpointMetadata:
            authentication: NoAuthentication
            seedUrlConnections:
              - seedUrl: <url>
        enableIdentityCrawler: false
        repositoryConfigurations:
          attachment:
            fieldMappings:
              - dataSourceFieldName: category
                indexFieldName: _category
                indexFieldType: STRING
              - dataSourceFieldName: sourceUrl
                indexFieldName: _source_uri
                indexFieldType: STRING
          webPage:
            fieldMappings:
              - dataSourceFieldName: category
                indexFieldName: _category
                indexFieldType: STRING
              - dataSourceFieldName: sourceUrl
                indexFieldName: _source_uri
                indexFieldType: STRING
        syncMode: FULL_CRAWL
        type: WEBCRAWLER
        version: 1.0.0
      Description: Website indexer
      DisplayName: !Sub "${SolutionPrefix}-web-ds"
      IndexId: !GetAtt QChatBusinessNativeIndex.IndexId
      RoleArn: !GetAtt QChatWebDataSourceRole.Arn
      SyncSchedule: "cron(33 22 ? * SAT *)"
```

I am not able to deploy it using the SAM framework.

![image](https://github.com/aws-cloudformation/aws-cloudformation-resource-provider-qbusiness/assets/141401509/7c6f2f81-c9a3-4232-9474-4e607a9e0f2a)

Despite using booleans or even some conditions like `!Condition [1, 1]`, I am still encountering the same issue. After conducting some research, I found this file:

https://github.com/aws-cloudformation/aws-cloudformation-resource-provider-qbusiness/blob/main/aws-qbusiness-datasource/src/main/java/software/amazon/qbusiness/datasource/translators/DocumentConverter.java

The method `convertToMapToDocument` is used to convert the configuration into a Document by using `ImmutableMap`. My guess is that by doing so, we are probably mapping everything to strings, which is why the errors appear. Correct me if I'm wrong. Thank you in advance.

**Comment by jregistr** [comment]
I copied and slightly modified your yaml template and confirmed it can be created successfully
```yml
Resources:
  QChatWebDataSource:
      Type: AWS::QBusiness::DataSource
      Properties:
        ApplicationId: !ImportValue TheApplicationID
        Configuration:
          additionalProperties:
            crawlDepth: 2
            maxFileSize: 50
            maxLinksPerUrl: 100
            rateLimit: 300
            proxy: {}
            exclusionURLCrawlPatterns: []
            exclusionURLIndexPatterns: []
            exclusionFileIndexPatterns: []
            inclusionURLCrawlPatterns: []
            inclusionURLIndexPatterns: []
            inclusionFileIndexPatterns: []
            includeSupportedFileType: false
            crawlSubDomain: true
            crawlAllDomain: false
            honorRobots: true
          connectionConfiguration:
            repositoryEndpointMetadata:
              authentication: NoAuthentication
              seedUrlConnections:
                - seedUrl: "https://en.wikipedia.org/wiki/Dijkstra's_algorithm"
          enableIdentityCrawler: false
          repositoryConfigurations:
            attachment:
              fieldMappings:
                - dataSourceFieldName: category
                  indexFieldName: _category
                  indexFieldType: STRING
                - dataSourceFieldName: sourceUrl
                  indexFieldName: _source_uri
                  indexFieldType: STRING
            webPage:
              fieldMappings:
                - dataSourceFieldName: category
                  indexFieldName: _category
                  indexFieldType: STRING
                - dataSourceFieldName: sourceUrl
                  indexFieldName: _source_uri
                  indexFieldType: STRING
          syncMode: FULL_CRAWL
          type: WEBCRAWLER
          version: 1.0.0
        Description: Website indexer
        DisplayName: "I-web-ds"
        IndexId: !ImportValue TheIndexId
        RoleArn: !ImportValue TheDataSourceRoleArn
        SyncSchedule: "cron(33 22 ? * SAT *)"
```
